### ISSUE TITLE
Authentication error in source 'oauth2'. The reason was: 'Error on oauth2 linkback endpoint.'

### ISSUE THREAD

**Issue by janwout** [cirrusidentity/simplesamlphp-module-authoauth2#2]
I configured simplesamlphp with this module, when I come back from my openid provider, I get the following error message:

Authentication error in source 'oauth2'. The reason was: 'Error on oauth2 linkback endpoint.'

What does this error mean?

**Comment by pradtke** [comment]
Hmm, I think these lines in OAuth2ResponseHandler are masking the error and SSP isn't logging the root cause.

```php
        try {
            $source->finalStep($state, $request['code']);
        } catch (\Exception $e) {
            \SimpleSAML_Auth_State::throwException($state, new \SimpleSAML_Error_AuthSource($sourceId, 'Error on oauth2 linkback endpoint.', $e));
        }
```
https://github.com/cirrusidentity/simplesamlphp-module-authoauth2/blob/a724cc18c874ae3c7c57c794222f87675e1fb492/lib/OAuth2ResponseHandler.php#L70-L74

Try commenting out the try/catch parts so you are left with

            $source->finalStep($state, $request['code']);

And then re-run your test, and the error should bubble up better.

**Comment by janwout** [comment]
thanks, got

```
League\\OAuth2\\Client\\Provider\\Exception\\IdentityProviderException: invalid_grant in /simplesaml/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222\nStack trace:\n#0 /simplesaml/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(613): League\\OAuth2\\Client\\Provider\\GenericProvider->checkResponse(Object(GuzzleHttp\\Psr7\\Response), Array)\n#1 /simplesaml/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(528): League\\OAuth2\\Client\\Provider\\AbstractProvider->getParsedResponse(Object(GuzzleHttp\\Psr7\\Request))\n#2 /simplesaml/modules/authoauth2/lib/Auth/Source/OAuth2.php(141): League\\OAuth2\\Client\\Provider\\AbstractProvider->getAccessToken(Object(League\\OAuth2\\Client\\Grant\\AuthorizationCode), Array)\n#3 /simplesaml/modules/authoauth2/lib/OAuth2ResponseHandler.php(71): SimpleSAML\\Module\\authoauth2\\Auth\\Source\\OAuth2->finalStep(Array, '500afbb1774447e...')\n#4 /simplesaml/modules/authoauth2/lib/OAuth2ResponseHandler.php(38): SimpleSAML\\Module\\authoauth2\\OAuth2ResponseHandler->handleResponseFromRequest(Array)\n#5 /simplesaml/modules/authoauth2/www/linkback.php(5): SimpleSAML\\Module\\authoauth2\\OAuth2ResponseHandler->handleResponse()\n#6 /simplesaml/www/module.php(135): require('/simplesaml/mod...')\n#7 {main}, referer: https://bestandendelen2.pleio.nl/simplesaml/module.php/core/authenticate.php
```

**Comment by pradtke** [comment]
Your OIDC server is responding with an error that says `invalid_grant`. RFC 6749 says the server should return that error_code when

> The provided authorization grant (e.g., authorization
> code, resource owner credentials) or refresh token is
> invalid, expired, revoked, does not match the redirection
> URI used in the authorization request, or was issued to
> another client.

So the area of the code where this is happening is when the module tries to convert the `authorization code` into an access token. The `authorization code` was just generated so I doubt it is invalid, expired or revoked. The module also uses the same redirect uri and client id in both the authorize redirect and the token endpoint. Nothing stands out as being a cause.

The underlying OAuth2 library is reporting just an error code, though the server may also include an additional message. To see that you can re-enable the try-catch and change the exception type to `IdentityProviderException` and then log `$e->getResponseBody()` before the `SimpleSAML_Auth_State::throwException` call. Then you would see the whole error response in the SSP logs.  That might provide some more hints.

The other option is user `curl` on the command line to interact with the server. The first step is get a valid code AND ensure the module doesn't try to use it. This can be done by constructing an authorize url with an invalid state value. e.g.

https://account.pleio.nl/openid/authorize?state=invalid-state&scope=openid&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fbestandendelen2.pleio.nl%2Fsimplesaml%2Fmodule.php%2Fauthoauth2%2Flinkback.php&client_id=809805

If you log in with the above it will redirect you back to your SSP instance with an `authorization_code` (which you should capture) and then your SSP instance will report an error about an invalid state parameter. The state check happens prior to consuming the `authorization_code` so you know SSP hasn't used it.

Now you can use the code and try to get an access token

```
curl -d "code=REPLACE" \
    -d "client_secret=REPLACE_SECRET" \
    -d "client_id=809805" \
    -d "redirect_uri=https://bestandendelen2.pleio.nl/simplesaml/module.php/authoauth2/linkback.php" \
    -d 'grant_type=authorization_code' \
   https://account.pleio.nl/openid/token
```
